---
apiVersion: v1
kind: Secret
metadata:
    name: mysql-root-password
type: Opaque
data:
   ROOT_PASSWORD: bWFudGVjaGFjY29yZGlvbg==

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: mysql:5.6
          ports:
            - name: tcp
              protocol: TCP
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
               secretKeyRef:
                key: ROOT_PASSWORD
                name: mysql-root-password
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        storageClassName: accordion-storage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi